Fetch organisation list
HackBrexit/MinistersUnderTheInfluence pull request #90
Opened 2016-11-22 22:15 UTC by Greatlemer

Each **Pull Request** should relate to a single feature, therefore a single **Issue**. The smaller the **Pull Request** the faster it can be reviewed & merged. It should not be merged by the author.

## Issues to close

Fixes #86

## Notes

This is just a rough script that scans all the available csv files for what might be in the organisation column.
Comments for improvements very much welcome.

2016-11-23 09:00 UTC, felipesere commented on src/python/org_fetcher/fetch_orgs.py
> +    if not filename_lower.endswith('.csv'):
I think we could extract a method `is_csv(filename)` to make the intent a bit more obvious and potentially make the following comment obsolete.

2016-11-23 09:00 UTC, felipesere commented on src/python/org_fetcher/fetch_orgs.py
> +    if not 'meetings' in filename_lower:
Similar as above 😄 Maybe `contains_meetings(filename_lower)`?

2016-11-23 09:00 UTC, felipesere commented on src/python/org_fetcher/fetch_orgs.py
> +    if 'gift' in filename_lower:
Same as above 😄 Maybe `contains_gift(filename_lower)`?

Come to think of it, we could take this a step further and a function called `should_skip(filename)` that just calls the three little functions from above:
```
function should_skip($filename) {
  return is_csv($filename) || contains_meetings($filename) || contains_gift($filename)
}
```

That method explains when we skip entire files 😸

2016-11-23 09:00 UTC, felipesere commented on src/python/org_fetcher/fetch_orgs.py
> +            if first_row and not row[1]:
I'd propose a similar pattern as above with `should_skip`. The comments can then be either removed or moved down to that function, to keep the main algorithm neat and tidy 😺

2016-11-23 09:00 UTC, felipesere commented on src/python/org_fetcher/fetch_orgs.py
> +                for index, col in enumerate(row):
We could extract this for loop into something like `find_organisation(row)`.
Make sure to return `None` to maintain the original flow of the code.

2016-11-23 09:00 UTC, felipesere commented on src/python/org_fetcher/fetch_orgs.py
> +                    if 'organisation' in col.lower() or 'organization' in col.lower():
👍 for catching American and British spelling!!!

2016-11-23 09:23 UTC, felipesere requested changes
Thanks for this PR!

I have left some comments around extracting functions to further surface the intent of the code.

2016-11-23 22:36 UTC, Greatlemer commented
@felipesere I've updated my pull request with a lot more code extracted into bitesize functions.

I guess I was being a bit lazy with this one earlier as it was intended more as a one-shot script but you never know when someone else will want to modify and re-use it I suppose.

2016-11-24 20:33 UTC, felipesere approved these changes
Looks great!

2016-11-24 20:34 UTC, felipesere approved these changes
Looks great!

2016-11-24 20:34 UTC, felipesere commented
How does the whole 'review required' thing work? @eddiejaoude @elischutze

2016-11-24 22:55 UTC, eddiejaoude commented
You need someone else to `Accept` the **Pull Request**, then you or they can merge it :)

2016-11-24 22:56 UTC, eddiejaoude commented
https://help.github.com/articles/about-pull-request-reviews/

2016-11-24 23:41 UTC, Greatlemer commented
@eddiejaoude, Felipe was the reviewer, I am the author, is there a reason why he wouldn't have been able to approve it?

2016-11-25 07:55 UTC, eddiejaoude commented
@Greatlemer oh i see.

@felipesere you need to accept the invite to the **HackBrexit** organisation. Then you will be able to approve the pull request & merge it.

<img width="1058" alt="screenshot 2016-11-25 07 55 19" src="https://cloud.githubusercontent.com/assets/624760/20618020/8a491b28-b2e4-11e6-9968-9a249871719b.png">

2016-11-29 17:14 UTC, elischutze approved these changes

2016-11-29 17:15 UTC, elischutze commented
Looks like you guys have this sorted so I'm going to go ahead and approve it. 👍

2016-11-29 20:42 UTC, merged